### ISSUE TITLE
please help ejs 

### ISSUE THREAD

**Issue by ulumind** [XploitWizer/XploitSPY#119]
SyntaxError: Unexpected identifier in /root/XploitSPY/server/assets/views/welcome.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/root/XploitSPY/server/node_modules/ejs/lib/ejs.js:673:12)
    at Object.compile (/root/XploitSPY/server/node_modules/ejs/lib/ejs.js:398:16)
    at handleCache (/root/XploitSPY/server/node_modules/ejs/lib/ejs.js:235:18)
    at tryHandleCache (/root/XploitSPY/server/node_modules/ejs/lib/ejs.js:274:16)
    at View.exports.renderFile [as engine] (/root/XploitSPY/server/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/root/XploitSPY/server/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/XploitSPY/server/node_modules/express/lib/application.js:640:10)
    at Function.render (/root/XploitSPY/server/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/root/XploitSPY/server/node_modules/express/lib/response.js:1012:7)

**Comment by r4vanan** [comment]
It will be patched in new version

**Comment by Clperson** [comment]
I have the same error how to deal with it ?
