### ISSUE TITLE
Can't log in after installation

### ISSUE THREAD

**Issue by LuckyFishGeek** [XploitWizer/XploitSPY#132]
![Snipaste_2022-12-28_16-28-00](https://user-images.githubusercontent.com/29472751/209782536-05514210-1a85-4c58-8710-99a6006ba8b4.png)
![Snipaste_2022-12-28_16-28-08](https://user-images.githubusercontent.com/29472751/209782548-afc4db8c-716b-46fe-9339-ad1316b79c19.png)

**Comment by Coleiras** [comment]
Error after install

FetchError: invalid json response body at http://authxspy.herokuapp.com/ reason: Unexpected token < in JSON at position 0
    at /var/www/XploitSPY/server/node_modules/node-fetch/lib/index.js:273:32
    at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/118902604/209880322-1a95a170-3137-476d-885e-9472cad8bea9.png)

**Comment by ws-rush** [comment]
@Coleiras  I fixed this problem, solution is in this PR -> https://github.com/XploitWizer-Community/XploitSPY/pull/135

@LuckyFishGeek the error you shared is css error it doesnt effect any functionality I think, the problem I fixed make login work

**Comment by ws-rush** [comment]
@LuckyFishGeek please make this open until PR merged
